CREATE TABLE census.characteristics (
	demographics_code      char(4),
	characteristics_code   char(2),
	characteristics_text   text,
	display_level          text,
	selectable             bool,
	sort_sequence          smallint
);
CREATE INDEX ON census.characteristics (characteristics_code);

\COPY census.characteristics FROM './data/raw_data/cx.characteristics.txt' WITH ( FORMAT CSV, HEADER true, DELIMITER E'\t' );
